// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: satellite_communication.proto
// Protobuf C++ Version: 5.26.1

#include "satellite_communication.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace satellitecommunication {

inline constexpr LEDResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : status_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        success_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR LEDResponse::LEDResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct LEDResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LEDResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~LEDResponseDefaultTypeInternal() {}
  union {
    LEDResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LEDResponseDefaultTypeInternal _LEDResponse_default_instance_;

inline constexpr LEDRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : command_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR LEDRequest::LEDRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct LEDRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LEDRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~LEDRequestDefaultTypeInternal() {}
  union {
    LEDRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LEDRequestDefaultTypeInternal _LEDRequest_default_instance_;
}  // namespace satellitecommunication
static ::_pb::Metadata file_level_metadata_satellite_5fcommunication_2eproto[2];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_satellite_5fcommunication_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_satellite_5fcommunication_2eproto = nullptr;
const ::uint32_t
    TableStruct_satellite_5fcommunication_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::satellitecommunication::LEDRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::satellitecommunication::LEDRequest, _impl_.command_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::satellitecommunication::LEDResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::satellitecommunication::LEDResponse, _impl_.status_),
        PROTOBUF_FIELD_OFFSET(::satellitecommunication::LEDResponse, _impl_.success_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::satellitecommunication::LEDRequest)},
        {9, -1, -1, sizeof(::satellitecommunication::LEDResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::satellitecommunication::_LEDRequest_default_instance_._instance,
    &::satellitecommunication::_LEDResponse_default_instance_._instance,
};
const char descriptor_table_protodef_satellite_5fcommunication_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\035satellite_communication.proto\022\026satelli"
    "tecommunication\"\035\n\nLEDRequest\022\017\n\007command"
    "\030\001 \001(\t\".\n\013LEDResponse\022\016\n\006status\030\001 \001(\t\022\017\n"
    "\007success\030\002 \001(\0102\275\001\n\nLEDControl\022V\n\tTurnOnL"
    "ED\022\".satellitecommunication.LEDRequest\032#"
    ".satellitecommunication.LEDResponse\"\000\022W\n"
    "\nTurnOffLED\022\".satellitecommunication.LED"
    "Request\032#.satellitecommunication.LEDResp"
    "onse\"\000b\006proto3"
};
static ::absl::once_flag descriptor_table_satellite_5fcommunication_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_satellite_5fcommunication_2eproto = {
    false,
    false,
    334,
    descriptor_table_protodef_satellite_5fcommunication_2eproto,
    "satellite_communication.proto",
    &descriptor_table_satellite_5fcommunication_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_satellite_5fcommunication_2eproto::offsets,
    file_level_metadata_satellite_5fcommunication_2eproto,
    file_level_enum_descriptors_satellite_5fcommunication_2eproto,
    file_level_service_descriptors_satellite_5fcommunication_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_satellite_5fcommunication_2eproto_getter() {
  return &descriptor_table_satellite_5fcommunication_2eproto;
}
namespace satellitecommunication {
// ===================================================================

class LEDRequest::_Internal {
 public:
};

LEDRequest::LEDRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:satellitecommunication.LEDRequest)
}
inline PROTOBUF_NDEBUG_INLINE LEDRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : command_(arena, from.command_),
        _cached_size_{0} {}

LEDRequest::LEDRequest(
    ::google::protobuf::Arena* arena,
    const LEDRequest& from)
    : ::google::protobuf::Message(arena) {
  LEDRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:satellitecommunication.LEDRequest)
}
inline PROTOBUF_NDEBUG_INLINE LEDRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : command_(arena),
        _cached_size_{0} {}

inline void LEDRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
LEDRequest::~LEDRequest() {
  // @@protoc_insertion_point(destructor:satellitecommunication.LEDRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void LEDRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.command_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
LEDRequest::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(LEDRequest, _impl_._cached_size_),
              false,
          },
          &LEDRequest::MergeImpl,
          &LEDRequest::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void LEDRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:satellitecommunication.LEDRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.command_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* LEDRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 49, 2> LEDRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_LEDRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::satellitecommunication::LEDRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string command = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(LEDRequest, _impl_.command_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string command = 1;
    {PROTOBUF_FIELD_OFFSET(LEDRequest, _impl_.command_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\41\7\0\0\0\0\0\0"
    "satellitecommunication.LEDRequest"
    "command"
  }},
};

::uint8_t* LEDRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:satellitecommunication.LEDRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string command = 1;
  if (!this->_internal_command().empty()) {
    const std::string& _s = this->_internal_command();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "satellitecommunication.LEDRequest.command");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:satellitecommunication.LEDRequest)
  return target;
}

::size_t LEDRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:satellitecommunication.LEDRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string command = 1;
  if (!this->_internal_command().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_command());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void LEDRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<LEDRequest*>(&to_msg);
  auto& from = static_cast<const LEDRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:satellitecommunication.LEDRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_command().empty()) {
    _this->_internal_set_command(from._internal_command());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void LEDRequest::CopyFrom(const LEDRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:satellitecommunication.LEDRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool LEDRequest::IsInitialized() const {
  return true;
}

void LEDRequest::InternalSwap(LEDRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.command_, &other->_impl_.command_, arena);
}

::google::protobuf::Metadata LEDRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_satellite_5fcommunication_2eproto_getter,
                                   &descriptor_table_satellite_5fcommunication_2eproto_once,
                                   file_level_metadata_satellite_5fcommunication_2eproto[0]);
}
// ===================================================================

class LEDResponse::_Internal {
 public:
};

LEDResponse::LEDResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:satellitecommunication.LEDResponse)
}
inline PROTOBUF_NDEBUG_INLINE LEDResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : status_(arena, from.status_),
        _cached_size_{0} {}

LEDResponse::LEDResponse(
    ::google::protobuf::Arena* arena,
    const LEDResponse& from)
    : ::google::protobuf::Message(arena) {
  LEDResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.success_ = from._impl_.success_;

  // @@protoc_insertion_point(copy_constructor:satellitecommunication.LEDResponse)
}
inline PROTOBUF_NDEBUG_INLINE LEDResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : status_(arena),
        _cached_size_{0} {}

inline void LEDResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.success_ = {};
}
LEDResponse::~LEDResponse() {
  // @@protoc_insertion_point(destructor:satellitecommunication.LEDResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void LEDResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.status_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
LEDResponse::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(LEDResponse, _impl_._cached_size_),
              false,
          },
          &LEDResponse::MergeImpl,
          &LEDResponse::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void LEDResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:satellitecommunication.LEDResponse)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.status_.ClearToEmpty();
  _impl_.success_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* LEDResponse::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 49, 2> LEDResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_LEDResponse_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::satellitecommunication::LEDResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool success = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(LEDResponse, _impl_.success_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(LEDResponse, _impl_.success_)}},
    // string status = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(LEDResponse, _impl_.status_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string status = 1;
    {PROTOBUF_FIELD_OFFSET(LEDResponse, _impl_.status_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bool success = 2;
    {PROTOBUF_FIELD_OFFSET(LEDResponse, _impl_.success_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
    "\42\6\0\0\0\0\0\0"
    "satellitecommunication.LEDResponse"
    "status"
  }},
};

::uint8_t* LEDResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:satellitecommunication.LEDResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string status = 1;
  if (!this->_internal_status().empty()) {
    const std::string& _s = this->_internal_status();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "satellitecommunication.LEDResponse.status");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // bool success = 2;
  if (this->_internal_success() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        2, this->_internal_success(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:satellitecommunication.LEDResponse)
  return target;
}

::size_t LEDResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:satellitecommunication.LEDResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string status = 1;
  if (!this->_internal_status().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_status());
  }

  // bool success = 2;
  if (this->_internal_success() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void LEDResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<LEDResponse*>(&to_msg);
  auto& from = static_cast<const LEDResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:satellitecommunication.LEDResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_status().empty()) {
    _this->_internal_set_status(from._internal_status());
  }
  if (from._internal_success() != 0) {
    _this->_impl_.success_ = from._impl_.success_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void LEDResponse::CopyFrom(const LEDResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:satellitecommunication.LEDResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool LEDResponse::IsInitialized() const {
  return true;
}

void LEDResponse::InternalSwap(LEDResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.status_, &other->_impl_.status_, arena);
        swap(_impl_.success_, other->_impl_.success_);
}

::google::protobuf::Metadata LEDResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_satellite_5fcommunication_2eproto_getter,
                                   &descriptor_table_satellite_5fcommunication_2eproto_once,
                                   file_level_metadata_satellite_5fcommunication_2eproto[1]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace satellitecommunication
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::std::false_type _static_init_ PROTOBUF_UNUSED =
    (::_pbi::AddDescriptors(&descriptor_table_satellite_5fcommunication_2eproto),
     ::std::false_type{});
#include "google/protobuf/port_undef.inc"
